# -*- coding: utf-8 -*-
"""validacion_datos

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LgWrxtv3_4C1O9P-PRy5wS4pY6NljzEu
"""

# Funciones para validación de datos

def validar_datos(df):
    pass